### PR TITLE
ci(tests): make tests actually run on `main`

### PR DESCRIPTION
**Pull request by clason**
Also prevent running duplicate tests and fix typos.

### CODE REVIEW

**Comment by clason** [comment]
Not sure why the Python test is failing here. @kiyoon @ribru17 @theleop any idea?

**Comment by kiyoon** [comment]
It seems like it's unable to locate the textobjects queries

**Comment by clason** [comment]
Yes, but why?

**Comment by kiyoon** [comment]
Honestly I don't know unless I try to set it up on my own again.. What were you trying to do in the PR exactly? I think the tests were alright it had no problem for a while

**Comment by clason** [comment]
> What were you trying to do in the PR exactly? I think the tests were alright it had no problem for a while

No, the tests on `main` were completely broken. I'm trying to fix them.

**Comment by clason** [comment]
OK, something is wrong with the `run_tests.sh` script; there's an unspecified error and then it just hangs. That's beyond my expertise, though.

**Comment by clason** [comment]
OK, things are working as far as I can see. I suspect the test failures (which are some, not all!)  are actually real regressions.

**Review by dundargoc — APPROVED** [review]

**Comment by clason** [comment]
Regressions will have to be fixed in a follow-up PR.

**Comment by clason** [comment]
First test failure is due to selection mode not being able to be specified anymore (see https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/ca93cb2c34b67ab22d01976fc90bc95627a3317f/scripts/minimal_init.lua#L69-L71)

**Pull request merged**
