### PR TITLE
CodeQL textobjects.scm

### PR DESCRIPTION
**Pull request by pwntester**

### CODE REVIEW

**Review by stsewd — APPROVED** [review]
Thanks!

**Comment by pwntester** [comment]
I was not able to define textobjects for `class.inner` and some functions inner. It seems a common problem for other languages, such as lua. Wondering if there is anything that can be done to help treesitter find the inner given an outer

**Comment by stsewd** [comment]
> I was not able to define textobjects for class.inner and some functions inner. It seems a common problem for other languages, such as lua. Wondering if there is anything that can be done to help treesitter find the inner given an outer

I think the best way is to have the language define a public node like `block` or for treesitter to allow access some anonymous nodes (those that start with `_`)

**Comment by pwntester** [comment]
Yep, but normally you cannot change the parser and it would be nice to be able to access those inner textobjects. Like Lua's `function_definition`, I cant see any nodes for the body and I cant probably ask for it, but I know functions body starts after parameter parentheses and finishes before the `end` keyword so maybe we can mix regexps and treesitter to define Textobjects when they are not available in the tree

**Comment by theHamsta** [comment]
We eventually need either `function.inner.end` in addition to `function.inner.end` then we could define such objects by the first and last node.

**Comment by pwntester** [comment]
Thats a brilliant idea. should I open an issue?

**Comment by theHamsta** [comment]
You can. there's already the code for `function.inner.start`. it's not the most elegant solution but you can already append extra nodes at the start of a node (c++ appends template declarations to function,outer). 

We would need to have textobjects with start and end only or change the code that you don't need to have your cursor in the range of the end  node to append nodes at the start . probably the latter is better.

**Pull request merged**
