### PR TITLE
Remove undocumented captures, fix CI (and touch up CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ribru17**
Mentions the new formatter check, gives a few touch-ups.

EDIT: It also fixes the capture group CI check, which was dependent upon the `h3` heading of `Textobjects` having the same name (case insensitive) as the query group (what??? hopefully this is addressed in `main` :joy:)

### CODE REVIEW

**Comment by clason** [comment]
> EDIT: It also fixes the capture group CI check, which was dependent upon the h3 heading of Textobjects having the same name (case insensitive) as the query group (what??? hopefully this is addressed in main 😂)

No, that's the same way it works in nvim-treesitter (which has to test multiple different queries). We can talk about pulling the queries into the main repo, but only if we know they're stable (otherwise adjusting the queries to plugin changes becomes impossible).

**Comment by ribru17** [comment]
Ah, makes sense. I will amend this to remove all undocumented captures to "stabilize" things; they're query changes, so would it be fine to target `master`? Or do you think it should be `main` since it's a bit breaking maybe?

**Comment by clason** [comment]
No, query changes should target master. (Nvim-treesitter had a similar "consolidation" phase recently.)

**Comment by ribru17** [comment]
Oh, right. Thanks!

**Comment by clason** [comment]
Alternatively, if `@function.outer.start` is useful, we could add it to the documentation and other queries. What does Helix do?

**Comment by ribru17** [comment]
That sounds fine. I personally didn't think it looked too useful, and helix only has `@function.(inside|around)`

**Comment by clason** [comment]
That's fine, then.

**Review by clason — APPROVED** [review]

**Pull request merged**
