### PR TITLE
Queries for odin

### PR DESCRIPTION
**Pull request by xb-bx**
Hello. 
This PR introduces queries for [odin](https://odin-lang.org/)

Thx for great plugin!

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]
Thank you! Looks good to me. I didn't have the time yet to test personally but might have on weekend. But merging would be also fine to me.

**Comment by ribru17** [comment]
Would you mind rebasing on the latest `master` and running the formatter? I think then this will be good to merge. Thank you for the contribution!

**Comment by xb-bx** [comment]
Okay, but what formatter should i use?

**Comment by ribru17** [comment]
It should be the one found [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/main/scripts/format-queries.lua): this is the one used by the main `nvim-treesitter` repo. It's probably enough to just do `nvim -l /path/to/nvim-treesitter/scripts/format-queries.lua /path/to/nvim-treesitter-textobjects/queries/odin/textobjects.scm` (if you have an up-to-date version of the `nvim-treesitter` plugin)

**Comment by ribru17** [comment]
Thank you for the change and feedback! I will get on that :+1:

**Review by ribru17 — APPROVED** [review]

**Pull request merged**
