### PR TITLE
feat: improve PHP queries

### PR DESCRIPTION
**Pull request by laytan**
- excludes the braces for all the inside queries
- add query for if statements
- add query for plain for loops

### CODE REVIEW

**Comment by laytan** [comment]
I have one addition to make which I forgot

**Comment by gbprod** [comment]
We can also introduce textobjects for `call` (I use it for some days) : 

```query
; call

(function_call_expression) @call.outer

(member_call_expression) @call.outer

(function_call_expression
    arguments: (arguments . "(" . (_) @_start (_)? @_end . ")"
    (#make-range! "call.inner" @_start @_end)))

(member_call_expression
    arguments: (arguments . "(" . (_) @_start (_)? @_end . ")"
    (#make-range! "call.inner" @_start @_end)))
```

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
@gbprod i think you can create a follow up PR.

Thank you @laytan !

**Comment by unansweredocd** [comment]
Thank you so much for adding this!

**Pull request merged**
