### PR TITLE
Add hooks support

### PR DESCRIPTION
**Pull request by glyh**
There are some good builtin commands in the nvim-treesitter-textobjects, however, it's hard for user to add their own command. 

Adding hooks in the modules will enable users to do what ever they want.

### CODE REVIEW

**Comment by theHamsta** [comment]
I'm not sure if most users including me would understand how and in which situation one could use this feature. Could you share a use case? What's the advantage over manually patching the function?

```lua
require 'module'.fun = function (...) before(...) require 'module'.fun(...) end
```

**Comment by glyh** [comment]
Well, the actually use case is that I want to know the query string given to this module, so that I can do different things on after different selection(for example) ... 

I think you're right that we can manually do this.....

**Comment by glyh** [comment]
I don't know why but this won't work(Called after setup treesitter)
```lua
local select =
  require "nvim-treesitter.configs".get_module("textobjects.select")

local selectfn = select.select_textobject
```

**Comment by theHamsta** [comment]
get_module is not named well. It will give you the config of module and whether it's enabled. Use require'nvim-treesitter.textobjects.share` to get the actual lua file

**Comment by glyh** [comment]
> equire'nvim-treesitter.textobjects.share

This is not working as well, I've tried it after require("nvim-treesitter.configs").setup :
```lua
require'nvim-treesitter.textobjects.share'
```

**Comment by theHamsta** [comment]
Are you using the exact path of the lua file? In this case the file was called `shared` https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/master/lua/nvim-treesitter/textobjects


I'm on mobile so it's difficult to avoid mistakes

**Comment by glyh** [comment]
Sorry but I'm testing another module, the shared one works, but `select` don't seem so:
```lua
local select = require'nvim-treesitter.textobjects.select' -- won't work
local shared = require'nvim-treesitter.textobjects.shared'
```

**Pull request closed without merging**
