### PR TITLE
fix(deprecation): use query.get_files to avoid deprecation

### PR DESCRIPTION
**Pull request by theHamsta**
See https://github.com/neovim/neovim/pull/22761

### CODE REVIEW

**Comment by theHamsta** [comment]
The only other usage in the check query script. I think we can wait for 0.9 as users are not annoyed by that.

**Comment by kiyoon** [comment]
Will it not break the older nightly 0.9 versions before the patch?

**Comment by theHamsta** [comment]
We can wait one day or just do the shorter `a or b`. With the version, the message is more clear.

**Comment by theHamsta** [comment]
If the deprecation warning would be less annoying, the right way would be to do an explicit version check in a few weeks. :smile:

**Comment by kiyoon** [comment]
True, I think normally it's not that annoying but using nvim-notify makes it very annoying

**Comment by theHamsta** [comment]
Is it ok now?

**Comment by kiyoon** [comment]
@theHamsta looks alright from the code but I haven't yet actually tested it

**Comment by kiyoon** [comment]
It works well on the stable and nightly neovim before the deprecation (my current installation). I think it will work with the master branch as well.

**Review by kiyoon — APPROVED** [review]

**Pull request merged**
