### PR TITLE
Fix typescript textobjects for nvim-treesitter/nvim-treesitter#1000

### PR DESCRIPTION
**Pull request by theHamsta**
@fsouza Some parameter queries will stop to work for typescript

### CODE REVIEW

**Comment by fsouza** [comment]
@theHamsta thanks for taking care of this!

**Comment by theHamsta** [comment]
If you have time you could look for the equivalent typscript nodes for the javascript nodes that stopped working.

**Comment by fsouza** [comment]
@theHamsta I can take a look later today. Will let you know!

**Comment by theHamsta** [comment]
We have the same problem in core. I out-commented all parameter queries until someone sorts out (actually kyazdani42 or steelsojka wanted to that)

**Comment by fsouza** [comment]
@theHamsta I may have to look into this later after merging. Can send a PR at some point :D

**Review by fsouza — APPROVED** [review]
Just tested it locally and it works with all cases that we had for javascript before, so we should be good. Will review core stuff.

**Pull request merged**
