### PR TITLE
ci: do README update via stefanzweifel/git-auto-commit-action@v4

### PR DESCRIPTION
**Pull request by theHamsta**
I tried it out here for a different repo: https://github.com/NVIDIA/VideoProcessingFramework/pull/446

### CODE REVIEW

**Comment by kiyoon** [comment]
Great!

Slightly unrelated, but how does VPF differ from PyAV? In my understanding PyAV is a python binding for ffmpeg so if nvidia decoder / encoder is installed on ffmpeg it can still use HW acceleration?

I also heard PyTorch's torchvision has video decoding feature that performs better than PyAV. I assume the nvidia one should be faster than both?

**Comment by theHamsta** [comment]
> Great!
> 
> Completely unrelated, but how does VPF differ from PyAV? In my understanding PyAV is a python binding for ffmpeg so if nvidia decoder / encoder is installed on ffmpeg it can still use HW acceleration?
> 
> I also heard PyTorch's torchvision has video decoding feature that performs better than PyAV. I assume the nvidia one (VPF) should be faster than both?

This is a legacy one. It is more or less the same scope as PyAV but with focus on NVENC/NVDEC. The next iteration will have narrower focus but easier to use with https://github.com/CvCuda/CV-CUDA and Torch.

torchvision seems to use FFmpeg but doesn't seem to open a HWcontext (which would allow them to use HW accerlation) https://github.com/pytorch/pytorch/blob/233742cb2f5cc645afc3a511185c3ec59924f7de/caffe2/video/video_decoder.cc

In general, NVDEC/NVENC are faster because they are physical hardware circuits which is faster than software written on CPU. FFmpeg has support for NVDEC/NVENC which would allow PyAV/torchvision to decode directly on GPU to CUDA tensors.

**Comment by theHamsta** [comment]
This change will work more or less like that https://github.com/theHamsta/nvim-treesitter-textobjects/commits/master (tested on my fork's master)

**Comment by kiyoon** [comment]
Thanks. I used to use DALI but because of lack of operations on video (e.g. it was hard to load frames the way I wanted to) I stopped using it. I also remember the dataloader is a custom class type so it would be incompatible with many libraries that assumes Pytorch dataloader to be used. It was a long time ago so I'm sure they improved things by now.  
CVCUDA looks great as well. I'll need to check it out. Is it new?

**Comment by theHamsta** [comment]
> Thanks. I used to use DALI but because of lack of operations on video (e.g. it was hard to load frames the way I wanted to) I stopped using it. I also remember the dataloader is a custom class type so it would be incompatible with many libraries that assumes Pytorch dataloader to be used. It was a long time ago so I'm sure they improved things by now. CVCUDA looks great as well. I'll need to check it out. Is it new?

DALI is also NVENC/NVDEC accelerated

> Is it new?
yes, it is still beginning of beta. Expect improvements.

**Comment by kiyoon** [comment]
Can you test on your repo what will happen if you modify the last section of readme by yourself? If you damage the section or completely remove it, will it fix the file or will it break things unexpectedly?

If the bot is opening a PR I feel more comfortable because it's okay to have some errors, but if it's directly writing to master we should be really careful not to mess anything up.

I also remember that this CI force pushes to the `update-readme` branch. However, we must never force push to master. I'd like to know if this is resolved

**Comment by theHamsta** [comment]
> Can you test on your repo what will happen if you modify the last section of readme by yourself? If you damage the section or completely remove it, will it fix the file or will it break things unexpectedly?
> 
> If the bot is opening a PR I feel more comfortable because it's okay to have some errors, but if it's directly writing to master we should be really careful not to mess anything up.
> 
> I also remember that this CI force pushes to the `update-readme` branch. However, we must never force push to master. I'd like to know if this is resolved

No, this will not work. Our script only replaces the text between the `<!--textobjectinfo-->`  comment tags. `<!--textobjectinfo-->` should not be removed. It will break the old and the new workflow.

**Comment by theHamsta** [comment]
> Can you test on your repo what will happen if you modify the last section of readme by yourself?

I don't understand, isn't this what I did here: https://github.com/theHamsta/nvim-treesitter-textobjects/commit/c5149451a5175c90e6e03f9f21b6ba76df511979

**Comment by kiyoon** [comment]
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/de9801d4f448df958d09fec60839e0a39d069610/scripts/update-readme.lua#L54-L58

How about you delete this line from the readme, so the lua script sees some unexpected README format?

**Comment by kiyoon** [comment]
Looks all good to me! The script got way simpler as well.

**Review by kiyoon — APPROVED** [review]

**Comment by kiyoon** [comment]
Wait, the master branch of this repo is protected. Did you also test with the protected master branch?

**Comment by theHamsta** [comment]
> Wait, the master branch of this repo is protected. Did you also test with the protected master branch?

No, but there are actually no protections that require a PR. I'll test tomorrow

**Comment by kiyoon** [comment]
If it works with another repo then it should be good!

**Comment by kiyoon** [comment]
image
If I try to change directly in master it shows something like this.

**Comment by theHamsta** [comment]
The protected branch will cause problems
```
M	README.md
Your branch is up to date with 'origin/master'.
INPUT_ADD_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
INPUT_COMMIT_USER_NAME: github-actions[bot]
INPUT_COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
INPUT_COMMIT_MESSAGE: Automated README update
INPUT_COMMIT_AUTHOR: theHamsta <theHamsta@users.noreply.github.com>
[master c5b060d] Automated README update
 Author: theHamsta <theHamsta@users.noreply.github.com>
 2 files changed, 364 insertions(+)
 create mode 100755 nvim.appimage
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
remote: Resolving deltas:   0% (0/1)        
remote: Resolving deltas: 100% (1/1)        
remote: Resolving deltas: 100% (1/1), completed with 1 local object.        
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected.        
To https://github.com/theHamsta/nvim-treesitter-textobjects
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/theHamsta/nvim-treesitter-textobjects'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
0s
```
https://github.com/theHamsta/nvim-treesitter-textobjects/actions/runs/4632484922/jobs/8196595276

**Comment by kiyoon** [comment]
Okay, we can either keep it as is and make it create a PR, or we can make the master branch unprotected. I like the first option, but either is okay

**Pull request closed without merging**
