### PR TITLE
Rust and Java comment text objects and fix trailing whitespace.

### PR DESCRIPTION
**Pull request by caojoshua**
* Rust and Java comment text objects
* Fix trailing whitespace in edited files

### CODE REVIEW

**Review by theHamsta — APPROVED** [review]
Thank you!

**Comment by caojoshua** [comment]
Think the check timed out. It was checking elm textobjects, so shouldn't be related to this change. I'll let the maintainers decide if they want to override or take some other action.

**Comment by theHamsta** [comment]
This is might be a regression due to the update of nightly nvim to tree-sitter v0.20.1 @maxxnino a timeout of query loading for elm that didn't happen before.

**Comment by maxxnino** [comment]
yeah, i think because of this. Because this never happen before, until recently

**Pull request merged**
