### PR TITLE
Add php statement queries

### PR DESCRIPTION
**Pull request by gbprod**
Not sure that is complete. 
Does conditionnals and loop should be considered as statement here ?

### CODE REVIEW

**Comment by gbprod** [comment]
Regarding to `c` textobjects, it seems that conditionnals and loop should be considered as statement.
I've completed this pull request.

**Comment by gbprod** [comment]
List comes from grammar : https://github.com/tree-sitter/tree-sitter-php/blob/master/grammar.js#L123

**Comment by unansweredocd** [comment]
Do you happen to know whether there is a textobject that selects a callback function?

**Comment by gbprod** [comment]
> Do you happen to know whether there is a textobject that selects a callback function?

Do you mean an anonymous function ? (like `$f = function() { return; };`)
Currently, the "function" textobject doesn't catch anon functions, it should IMHO.

**Comment by unansweredocd** [comment]
Yes I mean an anonymous function. I figured it would have its own textobject but what you're saying makes sense, function "should" catch anon functions.

> > Do you happen to know whether there is a textobject that selects a callback function?
> 
> Do you mean an anonymous function ? (like `$f = function() { return; };`) Currently, the "function" textobject doesn't catch anon functions, it should IMHO.

**Comment by gbprod** [comment]
Make sense, I'll try to make something in another pull request

**Pull request merged**
